## 1.2. Векторы. Основные понятия

In [23]:
import numpy as np

In [2]:
s = np.array([33,65,50,45])
s

array([33, 65, 50, 45])

In [3]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]
share_living_space 

0.5277310924369748

In [4]:
apartment = np.delete(apartment, [0, 1])
apartment

array([1.900e+01, 2.200e+01, 6.055e+04, 2.000e+00])

In [5]:
apartment = np.append(apartment, share_living_space)
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [6]:
len(apartment)

5

## 

In [30]:
x = np.array([3, 4, 5, 9])
y = np.array([1,5,3,6])
xs = 200*(x)
ys = 400*y 
ys - xs

array([-200, 1200,  200,  600])

## 1.7. --> Практика. Векторы


In [32]:
import pandas as pd

### Задача 1.

In [38]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
HutP=Hut_Paradise_DF.values
#HutP
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [36]:
HutP=Hut_Paradise_DF.values # Преобразуем Hut_Paradise_DF в массив numpy

print(HutP[4])

[40 33  1  6 20 16]


In [45]:
pd.Series(Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area'])

0    13
1    12
2    15
3    13
4    17
5     9
6    20
7    15
8    25
dtype: int64

In [46]:
Hut_Paradise_DF['1.Rent'] * 0.4

0    26.0
1    28.0
2    48.0
3    14.0
4    16.0
5    20.0
6    40.0
7    36.0
8    34.0
Name: 1.Rent, dtype: float64

In [49]:
Hut_Paradise_DF['Len'] = [10, 20, 30, 15, 5, 40, 20, 8, 20]
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area  Len
0      65      50        3        5                 8          37   10
1      70      52        2       12                 4          40   20
2     120      80        1       10                 5          65   30
3      35      33        1        3                10          20   15
4      40      33        1        6                20          16    5
5      50      44        2       13                12          35   40
6     100      80        4        8                 5          60   20
7      90      65        3       21                 1          50    8
8      85      65        2        5                10          40   20

In [51]:
Hut_Paradise_DF['Len'] @ Hut_Paradise_DF['5.Demo two weeks'] 

1348

### Задача 2.

In [52]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [55]:
z = 2*v -3*w

In [56]:
z@u

0

In [60]:
# Vectors normalization
u_norm=u/np.linalg.norm(u)
v_norm=v/np.linalg.norm(v)
w_norm=w/np.linalg.norm(w)
print(round(u_norm[2], 3))
print(round(v_norm[3], 3))
print(round(w_norm[0], 3))

0.289
0.667
0.213
