In [104]:
import numpy as np
import pandas as pd

In [105]:
### 9.2 О массивах NumPy

In [106]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [107]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3)

(3, 3)

In [108]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [109]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[0, 0, 5],
       [7, 4, 5],
       [7, 5, 8]])

In [110]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [111]:
np.array([i for i in range(11) if i%2]) # only odd numbers

array([1, 3, 5, 7, 9])

In [112]:
np.arange(1, 14, 2) # only odd numbers

array([ 1,  3,  5,  7,  9, 11, 13])

In [113]:
### 9.3 Индексирование массивов NumPy

In [114]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
#big_secret

In [115]:
np.shape(big_secret)

(5, 51)

In [116]:
sum(big_secret[:, 50])  # sum of the last column

3154.332495807108

In [117]:
big_secret[:, 0:5]  # first 5 elements from each line
np.trace(big_secret[:, 0:5])    # sum of diagonal elements (of first 5 columns)

121.37188663699624

In [118]:
big_secret[:, -5:]  # last 5 elements from each line
dg = np.diagonal(big_secret[:, -5:])    # diagonal elements (of first 5 columns)
np.prod(dg)     # product of array elements

341505315559.2347

In [119]:
def is_odd(num):
   return num % 2 != 0

In [120]:
big_secret[:, 0:5]

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

In [121]:
big_secret[0:5:2, 0:52:2] = -1   # both indexes (rows & columns) are even -> replace with -1 

In [122]:
big_secret[1:5:2, 1:52:2] = 1  # both indexes are odd -> replace with 1 

In [123]:
### 9.4 Операции с массивами

In [124]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [125]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T  # транспонирование

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [126]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))     # one-dimentional array to two-dimentional

array([[3, 2, 9, 3, 2],
       [7, 3, 9, 5, 2],
       [2, 4, 1, 4, 7],
       [1, 0, 0, 6, 9]])

In [127]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()  # n-dimentional array to one-dimentional

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [128]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[4, 2, 2, 9],
       [8, 9, 5, 1],
       [8, 0, 5, 0]])

In [129]:
my_array<5  # matrix of True/False
my_array[my_array<5]    # new array of values which correspond condition

array([4, 2, 2, 1, 0, 0])

In [130]:
mask = np.array([1, 0, 1, 0], dtype=bool)   # 1 - show row/column, 0 - hide row/column
my_array[:, mask]

array([[4, 2],
       [8, 5],
       [8, 5]])

In [131]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[3, 9, 6, 4, 6, 2],
       [4, 7, 8, 1, 1, 8],
       [2, 8, 0, 1, 5, 6],
       [4, 2, 7, 6, 3, 6]])

In [132]:
#np.sort(my_array, axis=1)  # sort values in rows
np.sort(my_array, axis=0)   # sort values in columns

array([[2, 2, 0, 1, 1, 2],
       [3, 7, 6, 1, 3, 6],
       [4, 8, 7, 4, 5, 6],
       [4, 9, 8, 6, 6, 8]])

In [133]:
# Exercises

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
np.shape(great_secret)

(100, 3)

In [134]:
sum(np.cos(great_secret[0, :]) )

0.16006721889793019

In [135]:
sum(great_secret[great_secret>50] )

5470.0

In [136]:
temp = great_secret.flatten()
temp[150]

7.0710678118654755

In [137]:
temp = np.sort(great_secret, axis=0) 
sum(temp[99, :])

115.12148016521353

In [138]:
### 9.5 Математические и статистические операции

In [150]:
students = pd.read_csv('students.csv')
students.head()

ID  height  weight  avg_mark
0   1     135      34       4.0
1   2     160      43       5.0
2   3     163      40       4.3
3   4     147      44       5.0
4   5     138      41       4.7

In [151]:
students = students.to_numpy()  # convert from Pandas to NumPy

In [154]:
np.mean(students[:,-1])     # mean mark

4.430000000000001

In [155]:
np.median(students[:,-1])   # median mark

4.449999999999999

In [157]:
np.median(students[:, 2])   # median weight

42.0

In [158]:
np.mean(students[:, 2]) - np.median(students[:, 2])

1.7999999999999972

In [163]:
corr = np.corrcoef(students[:,2], students[:,3])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [165]:
np.std(students[:,-1])

0.4517742799230607

In [167]:
np.std(students[:,2]) ** 2

60.36

In [168]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [171]:
my_array[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [175]:
my_sin = np.sin(my_array)
my_sin.sum()

-0.05812430261413351

In [180]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [179]:
my_sin[1:4, 1:4] = 1

In [181]:
my_sin.sum()

7.571718421269144

In [188]:
new_sin = my_sin[:, 0:4].reshape((10,2))  
new_sin[:, 0].sum()

2.4057172058139544

In [192]:
# Task 8
bigdata = np.arange(101, 1001, 2)   # all odd values from 100 to 1000
bigdata = np.square(bigdata)    # all array's elements squared
#bigdata

In [193]:
np.median(bigdata)

302501.0

In [194]:
np.std(bigdata)

292095.0301991155

In [205]:
bd_odd = bigdata[1:(np.size(bigdata)):2]
bd_even = bigdata[0:(np.size(bigdata)):2]

In [206]:
corr = np.corrcoef(bd_even, bd_odd)
corr

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])